site_name: mb6 ros-workspace
nav:
  - MobiSyst <: '..'
  - Home: 'index.md'
  - Install:
    - On Pi3:  'configure-pi3.md'
    - On Pi4:  'configure-pi4.md'
    - Station: 'configure-station.md'
    - Manual Install: 'install.md'
  - Robots:
    - Pibot: 'robot-pibot.md'
    - Ezbot: 'robot-ezbot.md'
    - Stage: 'robot-stage.md'
  - Packages:
    - Basic:    'pkg-basic.md'
    - Multibot: 'pkg-multibot.md'
  - F.A.Q: 'f.a.q.md'

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true

theme:
  name: readthedocs
  collapse_navigation: True
  titles_only: True
  # include_homepage_in_sidebar: False

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


extra_css:
  - style.css
