# Static Configuration
network:
  version: 2
  wifis:
    renderer: networkd
    wlan0:
      dhcp6: false
      dhcp4: false
      optional: true
      access-points:
        IoT IMT Nord Europe:
          password: c454079ec3ae4199b6bb654c299fa08a87c0923657e911a0c9be552e282a07eb
      addresses: [10.89.5.21/16]
      routes:
        - to: default
          via: 10.89.0.1
      nameservers:
        addresses: [193.48.235.163] # everest.mines-douai.fr
